volumes:
  open-webui:

networks:
  open-webui:

services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - target: 8080
        published: 3000 
        protocol: tcp
        mode: host
    volumes:
      - open-webui:/app/backend/data
    restart: always
    networks:
      - open-webui
